<?php
    
    echo "RAPPORT";
    echo "<br />";
    print_r($rapport);
    echo "<br />";
    echo "<br />";
    echo "CRI";
    echo "<br />";
    print_r($cri);
    echo "<br />";
    echo "<br />";
    echo "DATES";
    echo "<br />";
    print_r($dates);
    echo "<br />";
    echo "<br />";
    echo "ACTIONS";
    echo "<br />";
    print_r($actions);
    echo "<br />";
    echo "<br />";
    echo "RESEAU";
    echo "<br />";
    print_r($reseau);
    echo "<br />";
    echo "<br />";
    echo "ETAT";
    echo "<br />";
    print_r($etat);
    echo "<br />";
    echo "<br />";
    echo "INTERVENANTS";
    echo "<br />";
    print_r($inter);
    echo "<br />";
    echo "<br />";
    echo "PIECES";
    echo "<br />";
    print_r($pieces);